In [1]:
# load csv using pandas
import pandas as pd

In [11]:
# load monthly data
df = pd.read_csv('monthly_reports.csv')

# print MACD CROSS RF, MACD CROSS LSTM, MACD CROSS Bi-LSTM without the index to doll
print(df[['MACD CROSS RF', 'MACD CROSS LSTM', 'MACD CROSS Bi-LSTM']].round(2).to_string(index=False))

# save MACD CROSS LSTM to a csv file
df[['MACD CROSS Bi-LSTM']].round(2).to_csv('MACD_CROSS_Bi-LSTM.csv', index=False)

 MACD CROSS RF  MACD CROSS LSTM  MACD CROSS Bi-LSTM
          0.00           -27.19              -27.19
          0.00           388.19              388.19
          0.00           357.55              357.55
          0.00           357.55              357.55
          0.00           357.55              248.87
          0.00           341.44              192.33
        -42.25           530.01              359.94
        -42.25           484.28              319.29
       -178.14           322.46              175.46
       -108.60           434.35              274.92
        128.82           816.40              614.49
         81.04           983.06              762.63
        124.38          1263.87             1012.23
        124.38          1207.92              962.50
        124.38          2200.50             1844.75
        124.38          2572.70             2175.57
        124.38          1985.91             1654.01

In [3]:
# load data
data = pd.read_csv('daily_reports.csv', header=0)

# extract Date, Buy and Hold, LSTM columns
data = data[['Date', 'Buy and Hold', 'LSTM']]

# remane LSTM to AI Model
data.rename(columns={'LSTM': 'AI Model'}, inplace=True)

data

           Date  Buy and Hold     AI Model
0    2022-12-09    -15.662544   -15.662544
1    2022-12-10    -15.916927   -15.916927
2    2022-12-11    -17.326302   -17.326302
3    2022-12-12    -11.452150   -11.452150
4    2022-12-13     21.576025    21.576025
..          ...           ...          ...
526  2024-05-19   2807.838629  4744.366969
527  2024-05-20   3104.856676  5192.437602
528  2024-05-21   3029.498678  5078.755264
529  2024-05-22   2971.230917  4990.854637
530  2024-05-23   2902.703447  4887.476587

[531 rows x 3 columns]

In [5]:
# convert data to array of json objects
data_records = data.to_dict(orient='records')

# convert data to json string
import json
json_data = json.dumps(data_records)

# write data to file
with open('daily_reports.json', 'w') as f:
    f.write(data)